// <auto-generated />
namespace E_Commerce.DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AD0001 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AD0001));
        
        string IMigrationMetadata.Id
        {
            get { return "202103120756371_AD-0001"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
